//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMDK01Sesian2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MACAdress
    {
        public int IDMACAdress { get; set; }
        public string Adress { get; set; }
    }
}
